vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       products:
           uri_prefix: /api/v1/admin/load_list
           upload_destination: '%kernel.project_dir%/public/uploads'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
